model_types=('LSTM') #'NN'
for model in "${model_types[@]}"
do
    # SMILES
    # python ../train.py --train_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/SMILES/StratifiedKFold/input_train_[0-9].csv --test_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/SMILES/StratifiedKFold/input_test_[0-9].csv --feature_names PS_SMILES,Contact_angle,Thickness_um,Solvent_solubility_parameter_Mpa_sqrt,xw_wt_percent,Temp_C,Permeate_pressure_mbar --target_name J_Total_flux_kg_m_2h_1 --model_type "$model" --model_config ../"$model"/model_config.json --results_path ~/Research/Repos/da_for_polymers/da_for_polymers/training/PV_Wang/SMILES --random_state 22
    # # AUGMENTED SMILES
    # python ../train.py --train_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/augmentation/StratifiedKFold/input_train_[0-9].csv --test_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/augmentation/StratifiedKFold/input_test_[0-9].csv --feature_names Augmented_SMILES,Contact_angle,Thickness_um,Solvent_solubility_parameter_Mpa_sqrt,xw_wt_percent,Temp_C,Permeate_pressure_mbar --target_name J_Total_flux_kg_m_2h_1 --model_type "$model" --model_config ../"$model"/model_config.json --results_path ~/Research/Repos/da_for_polymers/da_for_polymers/training/PV_Wang/Augmented_SMILES --random_state 22
    # BRICS
    # python ../train.py --train_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/BRICS/StratifiedKFold/input_train_[0-9].csv --test_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/BRICS/StratifiedKFold/input_test_[0-9].csv --feature_names PS_pair_BRICS,Contact_angle,Thickness_um,Solvent_solubility_parameter_Mpa_sqrt,xw_wt_percent,Temp_C,Permeate_pressure_mbar --target_name J_Total_flux_kg_m_2h_1 --model_type "$model" --model_config ../"$model"/model_config.json --results_path ~/Research/Repos/da_for_polymers/da_for_polymers/training/PV_Wang/BRICS --random_state 22
    # FINGERPRINT
    # python ../train.py --train_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/fingerprint/StratifiedKFold/input_train_[0-9].csv --test_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/fingerprint/StratifiedKFold/input_test_[0-9].csv --feature_names PS_FP_radius_3_nbits_512,Contact_angle,Thickness_um,Solvent_solubility_parameter_Mpa_sqrt,xw_wt_percent,Temp_C,Permeate_pressure_mbar --target_name J_Total_flux_kg_m_2h_1 --model_type "$model" --model_config ../"$model"/model_config.json --results_path ~/Research/Repos/da_for_polymers/da_for_polymers/training/PV_Wang/fingerprint --random_state 22
    
    # SELFIES
    # python ../train.py --train_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/SMILES/StratifiedKFold/input_train_[0-9].csv --test_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/SMILES/StratifiedKFold/input_test_[0-9].csv --feature_names PS_SELFIES,Contact_angle,Thickness_um,Solvent_solubility_parameter_Mpa_sqrt,xw_wt_percent,Temp_C,Permeate_pressure_mbar --target_name J_Total_flux_kg_m_2h_1 --model_type "$model" --model_config ../"$model"/model_config.json --results_path ~/Research/Repos/da_for_polymers/da_for_polymers/training/PV_Wang/SELFIES --random_state 22
    
    # AUTOMATED FRAG
    # python ../train.py --train_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/automated_fragment/StratifiedKFold/input_train_[0-9].csv --test_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/automated_fragment/StratifiedKFold/input_test_[0-9].csv --feature_names polymer_automated_frag,Contact_angle,Thickness_um,Solvent_solubility_parameter_Mpa_sqrt,xw_wt_percent,Temp_C,Permeate_pressure_mbar --target_name J_Total_flux_kg_m_2h_1 --model_type "$model" --model_config ../"$model"/model_config.json --results_path ~/Research/Repos/da_for_polymers/da_for_polymers/training/PV_Wang/automated_frag --random_state 22
    
    # AUTOMATED FRAG STR
    # python ../train.py --train_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/automated_fragment/StratifiedKFold/input_train_[0-9].csv --test_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/automated_fragment/StratifiedKFold/input_test_[0-9].csv --feature_names polymer_automated_frag_SMILES,Contact_angle,Thickness_um,Solvent_solubility_parameter_Mpa_sqrt,xw_wt_percent,Temp_C,Permeate_pressure_mbar --target_name J_Total_flux_kg_m_2h_1 --model_type "$model" --model_config ../"$model"/model_config.json --results_path ~/Research/Repos/da_for_polymers/da_for_polymers/training/PV_Wang/automated_frag_SMILES --random_state 22
    
    # AUTOMATED FRAG AUGMENTED
    # python ../train.py --train_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/automated_fragment/StratifiedKFold/input_train_[0-9].csv --test_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/automated_fragment/StratifiedKFold/input_test_[0-9].csv --feature_names polymer_automated_frag_aug,Contact_angle,Thickness_um,Solvent_solubility_parameter_Mpa_sqrt,xw_wt_percent,Temp_C,Permeate_pressure_mbar --target_name J_Total_flux_kg_m_2h_1 --model_type "$model" --model_config ../"$model"/model_config.json --results_path ~/Research/Repos/da_for_polymers/da_for_polymers/training/PV_Wang/automated_frag_aug --random_state 22
    
    # AUTOMATED FRAG AUGMENTED STR
    # python ../train.py --train_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/automated_fragment/StratifiedKFold/input_train_[0-9].csv --test_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/automated_fragment/StratifiedKFold/input_test_[0-9].csv --feature_names polymer_automated_frag_aug_SMILES,Contact_angle,Thickness_um,Solvent_solubility_parameter_Mpa_sqrt,xw_wt_percent,Temp_C,Permeate_pressure_mbar --target_name J_Total_flux_kg_m_2h_1 --model_type "$model" --model_config ../"$model"/model_config.json --results_path ~/Research/Repos/da_for_polymers/da_for_polymers/training/PV_Wang/automated_frag_aug_SMILES --random_state 22
    
    # AUTOMATED FRAG AUGMENTED RECOMBINED SMILES
    # python ../train.py --train_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/automated_fragment/StratifiedKFold/input_train_[0-9].csv --test_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/automated_fragment/StratifiedKFold/input_test_[0-9].csv --feature_names polymer_automated_frag_aug_recombined_SMILES,Contact_angle,Thickness_um,Solvent_solubility_parameter_Mpa_sqrt,xw_wt_percent,Temp_C,Permeate_pressure_mbar --target_name J_Total_flux_kg_m_2h_1 --model_type "$model" --model_config ../"$model"/model_config.json --results_path ~/Research/Repos/da_for_polymers/da_for_polymers/training/PV_Wang/automated_frag_aug_recombined_SMILES --random_state 22
    
    # AUTOMATED FRAG AUGMENTED RECOMBINED FINGERPRINT
    # python ../train.py --train_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/automated_fragment/StratifiedKFold/input_train_[0-9].csv --test_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/automated_fragment/StratifiedKFold/input_test_[0-9].csv --feature_names polymer_automated_frag_aug_recombined_fp,Contact_angle,Thickness_um,Solvent_solubility_parameter_Mpa_sqrt,xw_wt_percent,Temp_C,Permeate_pressure_mbar --target_name J_Total_flux_kg_m_2h_1 --model_type "$model" --model_config ../"$model"/model_config.json --results_path ~/Research/Repos/da_for_polymers/da_for_polymers/training/PV_Wang/automated_frag_aug_recombined_fp --random_state 22
    
    # DIMER FP
    python ../train.py --train_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/circular_fingerprint/StratifiedKFold/input_train_[1-9].csv --test_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/circular_fingerprint/StratifiedKFold/input_test_[1-9].csv --feature_names 2mer_fp,Contact_angle,Thickness_um,Solvent_solubility_parameter_Mpa_sqrt,xw_wt_percent,Temp_C,Permeate_pressure_mbar --target_name J_Total_flux_kg_m_2h_1 --model_type "$model" --model_config ../"$model"/model_config.json --results_path ~/Research/Repos/da_for_polymers/da_for_polymers/training/PV_Wang/dimer_fp --random_state 22
    
    # TRIMER FP
    python ../train.py --train_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/circular_fingerprint/StratifiedKFold/input_train_[0-9].csv --test_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/circular_fingerprint/StratifiedKFold/input_test_[0-9].csv --feature_names 3mer_fp,Contact_angle,Thickness_um,Solvent_solubility_parameter_Mpa_sqrt,xw_wt_percent,Temp_C,Permeate_pressure_mbar --target_name J_Total_flux_kg_m_2h_1 --model_type "$model" --model_config ../"$model"/model_config.json --results_path ~/Research/Repos/da_for_polymers/da_for_polymers/training/PV_Wang/trimer_fp --random_state 22
    
    # POLYMER GRAPH FP
    python ../train.py --train_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/circular_fingerprint/StratifiedKFold/input_train_[0-9].csv --test_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/circular_fingerprint/StratifiedKFold/input_test_[0-9].csv --feature_names 3mer_circular_graph_fp,Contact_angle,Thickness_um,Solvent_solubility_parameter_Mpa_sqrt,xw_wt_percent,Temp_C,Permeate_pressure_mbar --target_name J_Total_flux_kg_m_2h_1 --model_type "$model" --model_config ../"$model"/model_config.json --results_path ~/Research/Repos/da_for_polymers/da_for_polymers/training/PV_Wang/polymer_graph_fp --random_state 22
    
    # OHE
    python ../train.py --train_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/ohe/StratifiedKFold/input_train_[0-9].csv --test_path ~/Research/Repos/da_for_polymers/da_for_polymers/data/input_representation/PV_Wang/ohe/StratifiedKFold/input_test_[0-9].csv --feature_names Polymer_ohe,Contact_angle,Thickness_um,Solvent_solubility_parameter_Mpa_sqrt,xw_wt_percent,Temp_C,Permeate_pressure_mbar --target_name J_Total_flux_kg_m_2h_1 --model_type "$model" --model_config ../"$model"/model_config.json --results_path ~/Research/Repos/da_for_polymers/da_for_polymers/training/PV_Wang/ohe --random_state 22
done